"""compliance_alerts

Revision ID: 059f83839cec
Revises: 4ccfd328b82b
Create Date: 2026-09-28 12:48:11.802350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059f83839cec'
down_revision: Union[str, Sequence[str], None] = '4ccfd328b82b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_iban', sa.String(), nullable=False),
    sa.Column('opened_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_iban'], ['accounts.iban'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_compliance_alerts_account_iban'), 'compliance_alerts', ['account_iban'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_alerts_account_iban'), table_name='compliance_alerts')
    op.drop_table('compliance_alerts')
    # ### end Alembic commands ###
