"""cards_and_transfers

Revision ID: 4c94aa981cd2
Revises: 059f83839cec
Create Date: 2026-09-28 16:27:23.326838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c94aa981cd2'
down_revision: Union[str, Sequence[str], None] = '059f83839cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_iban', sa.String(), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('stato', sa.String(length=32), nullable=False),
    sa.Column('limite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_iban'], ['accounts.iban'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_account_iban'), 'cards', ['account_iban'], unique=False)
    op.create_table('transfers',
    sa.Column('riferimento', sa.String(length=32), nullable=False),
    sa.Column('account_iban', sa.String(), nullable=False),
    sa.Column('destinatario', sa.String(length=64), nullable=False),
    sa.Column('importo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stato', sa.String(length=32), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_iban'], ['accounts.iban'], ),
    sa.PrimaryKeyConstraint('riferimento')
    )
    op.create_index(op.f('ix_transfers_account_iban'), 'transfers', ['account_iban'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_account_iban'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_cards_account_iban'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
