"""compliance_alerts amount

Revision ID: d370fc3bcb25
Revises: 4c94aa981cd2
Create Date: 2026-09-29 10:04:32.113969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd370fc3bcb25'
down_revision: Union[str, Sequence[str], None] = '4c94aa981cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_alerts', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_alerts', 'amount')
    # ### end Alembic commands ###
