"""app_users + chunk visibility

Revision ID: e3a64a9a0d2c
Revises: a1b2c3d4e5f6
Create Date: 2026-09-24 14:19:08.933058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'e3a64a9a0d2c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.add_column('document_chunks', sa.Column('visibility', sa.String(length=32), nullable=False))
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=False)
    op.alter_column('document_chunks', 'chunk_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_document_chunks_embedding'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_chunks_visibility'), 'document_chunks', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_visibility'), table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_embedding'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('document_chunks', 'chunk_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=True)
    op.drop_column('document_chunks', 'visibility')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
